# Generated by Django 3.2.23 on 2026-04-29 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startScan', '0007_alter_subdomain_origin_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanhistory',
            name='cfg_custom_dorks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
