# Generated by Django 3.2.23 on 2026-04-29 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('startScan', '0008_scanhistory_cfg_custom_dorks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=1000)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('discovered_date', models.DateTimeField(auto_now_add=True)),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='startScan.endpoint')),
            ],
        ),
    ]
