# Generated by Django 3.2.23 on 2026-04-29 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startScan', '0009_parameter'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameter',
            name='impact',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='parameter',
            name='value',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
