# Generated by Django 3.2.23 on 2026-04-30 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('startScan', '0010_auto_20260429_1403'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecretLeak',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tool_name', models.CharField(max_length=100)),
                ('secret_type', models.CharField(max_length=200)),
                ('source_url', models.CharField(max_length=5000)),
                ('match_content', models.TextField()),
                ('status', models.CharField(choices=[('unverified', 'Unverified'), ('verified', 'Verified'), ('false_positive', 'False Positive')], default='unverified', max_length=20)),
                ('discovered_date', models.DateTimeField(auto_now_add=True)),
                ('scan_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startScan.scanhistory')),
                ('subdomain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='startScan.subdomain')),
            ],
        ),
    ]
