# Generated by Django 3.2.23 on 2026-04-28 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_llmconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='ui_version',
            field=models.CharField(choices=[('v2', 'Version 2 (Default)'), ('v3', 'Version 3 (Cyberpunk)')], default='v2', max_length=2),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='v3_intensity',
            field=models.CharField(choices=[('clean', 'Clean'), ('script_kiddie', 'Script Kiddie'), ('hacker', 'Hacker')], default='clean', max_length=20),
        ),
    ]
