# Generated by Django 3.2.23 on 2026-04-29 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20260428_2054'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpiderfootAPIKey',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('module_name', models.CharField(max_length=200)),
                ('key_name', models.CharField(default='api_key', max_length=200)),
                ('key_value', models.CharField(max_length=500)),
            ],
        ),
    ]
