# Generated by Django 3.2.23 on 2026-04-30 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_spiderfootapikey'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeakLookupAPIKey',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=500)),
            ],
        ),
    ]
